{
 "title": "reth",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Connected peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reth_network_connected_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Highest block",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "reth_stage_progress", "legendFormat": "{{stage}}" }
   ]
  },
  { "title": "Stages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Headers: Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "reth_stages_headers_unexpected_errors",
     "legendFormat": "Unexpected errors"
    },
    {
     "expr": "reth_stages_headers_validation_errors",
     "legendFormat": "Validation errors"
    },
    {
     "expr": "reth_stages_headers_timeout_errors",
     "legendFormat": "Timeout errors"
    }
   ]
  },
  {
   "title": "Headers: Downloaded headers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "reth_stages_headers_headers_counter",
     "legendFormat": "Downloaded headers"
    },
    {
     "expr": "rate(reth_stages_headers_headers_counter[$__rate_interval])",
     "legendFormat": "Headers/s"
    }
   ]
  },
  {
   "title": "Sync progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 9 },
   "targets": [
    { "expr": "reth_stage_progress", "legendFormat": "{{stage}}" }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Discovery: Tracked peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    { "expr": "reth_network_tracked_peers", "legendFormat": "Tracked peers" }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "reth_network_outgoing_connections",
     "legendFormat": "Outgoing connections"
    },
    {
     "expr": "reth_network_incoming_connections",
     "legendFormat": "Incoming connections"
    },
    { "expr": "reth_network_connected_peers", "legendFormat": "Connected peers" }
   ]
  },
  {
   "title": "P2P errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "reth_p2pstream_disconnected_errors",
     "legendFormat": "P2P stream disconnected"
    },
    {
     "expr": "reth_network_pending_session_failures",
     "legendFormat": "Failed pending sessions"
    },
    {
     "expr": "reth_network_invalid_messages_received",
     "legendFormat": "Invalid messages"
    }
   ]
  }
 ]
}